version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install EB CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install awsebcli --upgrade --user
      - run:
          name: EB init
          command: |
            eb init --region us-east-1 --platform Node.js
      - run:
          name: Frontend install
          command: |
            npm run frontend:install
      - run:
          name: Backend install
          command: |
            npm run backend:install
      - run:
          name: Frontend build
          command: |
            npm run frontend:build
      - run:
          name: Backend build and zip
          command: |
            npm run backend:zip
      - run:
          name: Use env
          command: |
            eb use reactnd-contacts-server-dev
      - run:
          name: Backend deploy
          command: |
            eb deploy reactnd-contacts-server-dev
      - run:
          name: Frontend deploy
          command: |
            npm run frontend:deploy

