version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Frontend install
          command: |
            npm run frontend:install
      - run:
          name: Backend install
          command: |
            npm run backend:install
      - run:
          name: Frontend build
          command: |
            npm run frontend:build
      - run:
          name: Backend build and zip
          command: |
            npm run backend:zip
      - run:
          name: Backend deploy
          command: |
            npm run backend:deploy      
      - run:
          name: Frontend deploy
          command: |
            npm run frontend:deploy

