version: 2.1
orbs:
  node: circleci/node@4.1.0
  # eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install pip3 and ebcli
          command: |
              sudo apt-get update
              sudo apt-get upgrade
              sudo apt-get install python3-pip
              pip3 install awsebcli==3.20.3
      - run:
          name: Frontend install
          command: |
            npm run frontend:install
      - run:
          name: Backend install
          command: |
            npm run backend:install
      - run:
          name: Frontend build
          command: |
            npm run frontend:build
      - run:
          name: Backend build and zip
          command: |
            npm run backend:zip
      - run:
          name: Backend deploy
          command: |
            eb deploy   
      - run:
          name: Frontend deploy
          command: |
            npm run frontend:deploy

